### ISSUE TITLE
Please update

### ISSUE THREAD

**Issue by gitbugged** [r4sas/i2pd-reseed#1]
China is massively censoring, and it would be nice to have a github mirror for reseeding.
The readme says it's updated every 6 hours, but it hasn't been updated since last year.

**Comment by r4sas** [comment]
It updated every 6 hours by re-uploading [assets](https://github.com/r4sas/i2pd-reseed/releases/download/1.0/i2pseeds.su3) in release. Release not touched itself. Download su3 file and try locally check creation time by HEX editor at dimension 0x0028
![0x0028](https://user-images.githubusercontent.com/7023612/31625153-b216b9fc-b2ad-11e7-956c-440003fae48e.png)

**Comment by 5hanth** [comment]
https://github.com/r4sas/i2pd-reseed/releases/download/1.0/i2pseeds.su3 is broken.

**Comment by r4sas** [comment]
@5hanth, thank you for reporting, now fixed.

**Comment by 5hanth** [comment]
turns out this url can't be used directly as redirect isn't allowed by i2p reseeder. directly using redirected url isn't recognized as a url and exception still arises.

![screen shot 2018-11-08 at 5 01 26 pm](https://user-images.githubusercontent.com/4287700/48185470-6a12d580-e378-11e8-996c-fc76544c34ce.png)

and there is issue with using the downloaded file as well. 

![screen shot 2018-11-08 at 5 01 50 pm](https://user-images.githubusercontent.com/4287700/48185495-7e56d280-e378-11e8-88fb-9bf5000fc69b.png)

**Comment by r4sas** [comment]
In that case you can download it to local computer and reseed from it.
For info: i2pd support that link.
